### PR TITLE
fix select typo

### LINKED ISSUE #72: ConsistentHashLoadBalancer.sekectForKey(long hash) 是不是错别字了？
应该是 select 吧？╮(￣▽￣)╭

### PR DESCRIPTION
**Pull request by leizhiyuan**
1. fix #72 
2. optimize quickstart

### CODE REVIEW

File: example/src/test/java/com/alipay/sofa/rpc/quickstart/QuickStartClient.java [hunk 1]
```diff
@@ -32,9 +32,16 @@ public static void main(String[] args) {
 
         HelloService helloService = consumerConfig.refer();
 
+        //wait address to receive and connect successfully
```
Comment (ujjboy) [inline example/src/test/java/com/alipay/sofa/rpc/quickstart/QuickStartClient.java]: No need to sleep hear, you can use `consumerConfig.setConnectTimeout(10000)` (default is 3000) for waiting slow connection.

**Comment by leizhiyuan** [comment]
@ujjboy fixed
